### ISSUE TITLE
局域网调用 连接应该是没问题的 但是 一直卡住不返回信息

### ISSUE THREAD

**Issue by ThePeppy** [danbai225/WeChatFerry-go#3]
<img width="1340" alt="image" src="https://github.com/danbai225/WeChatFerry-go/assets/49603204/51ac93ff-6907-4e94-85a6-759ee8a7375c">
<img width="663" alt="image" src="https://github.com/danbai225/WeChatFerry-go/assets/49603204/1db6af01-da9b-4ef8-9a74-6eacb279af1d">

在虚拟机里起的服务 然后使用你的项目做rpc调用测试

**Comment by ThePeppy** [comment]
方便的话 辛苦帮忙给解答一下

**Comment by ThePeppy** [comment]
7600端口的http文档服务也可以访问 唯独rpc这块无响应
<img width="1549" alt="image" src="https://github.com/danbai225/WeChatFerry-go/assets/49603204/249adcca-1dc7-4db8-b419-2735e3c98cc1">

**Comment by danbai225** [comment]
先看看rpc端口是不是通的，可以看看用其他客户的连下。试试

**Comment by ThePeppy** [comment]
解决了 问题原因是：
我用的wechat-rest这个项目起的服务 我原本以为和原作者用的sdk和spy是一样的 改用原作者的sdk后连接和调用正常

正好说一下 防止后面有人跟我踏入一样的坑。。。 用这个库必须用原作者的sdk.dll和spy.dll wechat-rest那个不能用
