### ISSUE TITLE
接收消息部分貌似有问题 无消息返回

### ISSUE THREAD

**Issue by ThePeppy** [danbai225/WeChatFerry-go#4]
方便的话 麻烦看看 用的就是test里的demo

**Comment by danbai225** [comment]
我这边没有环境，你看看呢这个项目比较简单就是一个rpc客户端，确实有问题的话可以的话提个pr

**Comment by danbai225** [comment]
你看看下wcf那边的日志。这边断点调下

**Comment by ThePeppy** [comment]
Running tool: /Users/wangrui/.gvm/gos/go1.21.5/bin/go test -timeout 30s -run ^TestOnMSG$ changeme/wcf

=== RUN   TestOnMSG
2023-12-27 21:03:38     [INFO]: wcf_test.go:178 0
panic: test timed out after 30s
running tests:
        TestOnMSG (30s)

goroutine 37 [running]:
testing.(*M).startAlarm.func1()
        /Users/wangrui/.gvm/gos/go1.21.5/src/testing/testing.go:2259 +0x320
created by time.goFunc
        /Users/wangrui/.gvm/gos/go1.21.5/src/time/sleep.go:176 +0x38

goroutine 1 [chan receive]:
testing.(*T).Run(0x14000082ea0, {0x102778650?, 0x2d743001eea2?}, 0x10293bf78)
        /Users/wangrui/.gvm/gos/go1.21.5/src/testing/testing.go:1649 +0x350
testing.runTests.func1(0x1400009b170?)
        /Users/wangrui/.gvm/gos/go1.21.5/src/testing/testing.go:2054 +0x48
testing.tRunner(0x14000082ea0, 0x140000efc28)
        /Users/wangrui/.gvm/gos/go1.21.5/src/testing/testing.go:1595 +0xe8
testing.runTests(0x1400009eaa0?, {0x102c9dfe0, 0x10, 0x10}, {0x40?, 0x1028fcf40?, 0x102ca6740?})
        /Users/wangrui/.gvm/gos/go1.21.5/src/testing/testing.go:2052 +0x3b4
testing.(*M).Run(0x1400009eaa0)
        /Users/wangrui/.gvm/gos/go1.21.5/src/testing/testing.go:1925 +0x538
main.main()
        _testmain.go:77 +0x1a8

goroutine 17 [chan receive]:
github.com/kpango/fastime.(*fastime).StartTimerD.func1()
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/github.com/kpango/fastime@v1.1.9/fastime.go:231 +0xb8
created by github.com/kpango/fastime.(*fastime).StartTimerD in goroutine 1
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/github.com/kpango/fastime@v1.1.9/fastime.go:223 +0x210

goroutine 19 [select]:
github.com/danbai225/go-logs.splitLogByDay()
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/github.com/danbai225/go-logs@v0.3.2/logs.go:141 +0x54
created by github.com/danbai225/go-logs.init.0 in goroutine 1
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/github.com/danbai225/go-logs@v0.3.2/logs.go:90 +0xcc

goroutine 20 [sleep]:
time.Sleep(0xdf8475800)
        /Users/wangrui/.gvm/gos/go1.21.5/src/runtime/time.go:195 +0x10c
changeme/wcf.TestOnMSG(0x0?)
        /Users/wangrui/Dev/Golang/wey-assitant/wcf/wcf_test.go:186 +0x188
testing.tRunner(0x14000083040, 0x10293bf78)
        /Users/wangrui/.gvm/gos/go1.21.5/src/testing/testing.go:1595 +0xe8
created by testing.(*T).Run in goroutine 1
        /Users/wangrui/.gvm/gos/go1.21.5/src/testing/testing.go:1648 +0x33c

goroutine 34 [IO wait]:
internal/poll.runtime_pollWait(0x1031b0110, 0x72)
        /Users/wangrui/.gvm/gos/go1.21.5/src/runtime/netpoll.go:343 +0xa0
internal/poll.(*pollDesc).wait(0x140001aa080?, 0x14000308000?, 0x0)
        /Users/wangrui/.gvm/gos/go1.21.5/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        /Users/wangrui/.gvm/gos/go1.21.5/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x140001aa080, {0x14000308000, 0x8, 0x8})
        /Users/wangrui/.gvm/gos/go1.21.5/src/internal/poll/fd_unix.go:164 +0x200
net.(*netFD).Read(0x140001aa080, {0x14000308000?, 0x102cdd040?, 0x102e08f40?})
        /Users/wangrui/.gvm/gos/go1.21.5/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x14000204000, {0x14000308000?, 0x14000096c48?, 0x102e08f18?})
        /Users/wangrui/.gvm/gos/go1.21.5/src/net/net.go:179 +0x34
io.ReadAtLeast({0x129bfc028, 0x14000204000}, {0x14000308000, 0x8, 0x8}, 0x8)
        /Users/wangrui/.gvm/gos/go1.21.5/src/io/io.go:335 +0xa0
io.ReadFull(...)
        /Users/wangrui/.gvm/gos/go1.21.5/src/io/io.go:354
encoding/binary.Read({0x129bfc028, 0x14000204000}, {0x102947230?, 0x102cdbca0}, {0x10287a7a0, 0x14000096e88?})
        /Users/wangrui/.gvm/gos/go1.21.5/src/encoding/binary/binary.go:237 +0x94
go.nanomsg.org/mangos/v3/transport.(*conn).Recv(0x14000206000)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/transport/conn.go:53 +0x5c
go.nanomsg.org/mangos/v3/internal/core.(*pipe).RecvMsg(0x140002060c0)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/internal/core/pipe.go:170 +0x30
go.nanomsg.org/mangos/v3/protocol/xpair1.(*pipe).receiver(0x1400020e040)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/xpair1/xpair1.go:309 +0x44
created by go.nanomsg.org/mangos/v3/protocol/xpair1.(*socket).AddPipe in goroutine 20
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/xpair1/xpair1.go:266 +0x1a0

goroutine 35 [select]:
go.nanomsg.org/mangos/v3/protocol/xpair1.(*pipe).sender(0x1400020e040)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/xpair1/xpair1.go:356 +0x158
created by go.nanomsg.org/mangos/v3/protocol/xpair1.(*socket).AddPipe in goroutine 20
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/xpair1/xpair1.go:267 +0x1e0

goroutine 49 [select]:
go.nanomsg.org/mangos/v3/protocol/xpair1.(*socket).RecvMsg(0x1400031c150)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/xpair1/xpair1.go:126 +0x19c
go.nanomsg.org/mangos/v3/protocol/pair1.(*socket).RecvMsg(0x129bfa960?)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/pair1/pair1.go:55 +0x28
go.nanomsg.org/mangos/v3/internal/core.(*socket).RecvMsg(...)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/internal/core/socket.go:190
go.nanomsg.org/mangos/v3/internal/core.(*socket).Recv(0x1027804ee?)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/internal/core/socket.go:194 +0x2c
changeme/wcf.(*Client).OnMSG(0x1400009b1d0, 0x10293c030)
        /Users/wangrui/Dev/Golang/wey-assitant/wcf/wcf.go:446 +0x2a4
created by changeme/wcf.TestOnMSG in goroutine 20
        /Users/wangrui/Dev/Golang/wey-assitant/wcf/wcf_test.go:183 +0x178

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0x1031b0018, 0x72)
        /Users/wangrui/.gvm/gos/go1.21.5/src/runtime/netpoll.go:343 +0xa0
internal/poll.(*pollDesc).wait(0x14000302180?, 0x140003081f8?, 0x0)
        /Users/wangrui/.gvm/gos/go1.21.5/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        /Users/wangrui/.gvm/gos/go1.21.5/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x14000302180, {0x140003081f8, 0x8, 0x8})
        /Users/wangrui/.gvm/gos/go1.21.5/src/internal/poll/fd_unix.go:164 +0x200
net.(*netFD).Read(0x14000302180, {0x140003081f8?, 0x10294b328?, 0x3?})
        /Users/wangrui/.gvm/gos/go1.21.5/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x1400032c078, {0x140003081f8?, 0x19?, 0x102e08f18?})
        /Users/wangrui/.gvm/gos/go1.21.5/src/net/net.go:179 +0x34
io.ReadAtLeast({0x129bfc028, 0x1400032c078}, {0x140003081f8, 0x8, 0x8}, 0x8)
        /Users/wangrui/.gvm/gos/go1.21.5/src/io/io.go:335 +0xa0
io.ReadFull(...)
        /Users/wangrui/.gvm/gos/go1.21.5/src/io/io.go:354
encoding/binary.Read({0x129bfc028, 0x1400032c078}, {0x102947230?, 0x102cdbca0}, {0x10287a7a0, 0x1400033ce88?})
        /Users/wangrui/.gvm/gos/go1.21.5/src/encoding/binary/binary.go:237 +0x94
go.nanomsg.org/mangos/v3/transport.(*conn).Recv(0x1400030e540)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/transport/conn.go:53 +0x5c
go.nanomsg.org/mangos/v3/internal/core.(*pipe).RecvMsg(0x1400030e5a0)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/internal/core/pipe.go:170 +0x30
go.nanomsg.org/mangos/v3/protocol/xpair1.(*pipe).receiver(0x14000326120)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/xpair1/xpair1.go:309 +0x44
created by go.nanomsg.org/mangos/v3/protocol/xpair1.(*socket).AddPipe in goroutine 49
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/xpair1/xpair1.go:266 +0x1a0

goroutine 52 [select]:
go.nanomsg.org/mangos/v3/protocol/xpair1.(*pipe).sender(0x14000326120)
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/xpair1/xpair1.go:356 +0x158
created by go.nanomsg.org/mangos/v3/protocol/xpair1.(*socket).AddPipe in goroutine 49
        /Users/wangrui/.gvm/pkgsets/go1.21.5/global/pkg/mod/go.nanomsg.org/mangos/v3@v3.4.2/protocol/xpair1/xpair1.go:267 +0x1e0
FAIL    changeme/wcf    30.849s


报错内容

**Comment by ThePeppy** [comment]
sdk的服务只能连接一次的 这是原作者说的 我看你的客户端里好像onmsg又连接一次

**Comment by danbai225** [comment]
他接收消息是另外一个端口，至少我之前对接时候是这样的。现在不清楚

**Comment by danbai225** [comment]
你看你注入dll后开启消息接收有没有多监听一个端口

**Comment by danbai225** [comment]
我这边没window环境暂时没法调

**Comment by ThePeppy** [comment]
只有一个端口

**Comment by danbai225** [comment]
EnableRecvTxt()返回状态吗是多少

**Comment by danbai225** [comment]
发送消息那些接口正常吗

**Comment by ThePeppy** [comment]
都正常的 就这一个接收消息的不正常

**Comment by ThePeppy** [comment]
我在尝试重写一份接收消息的看看

**Comment by ThePeppy** [comment]
记录一下 sdk的测试代码部分 由于没有做RecvTxt=true 所以使用的朋友 会出现没有返回消息的问题 在使用的时候 一定要把RecvTxt设置为true 不是EnableRecvTxt就ok了 还有个状态要处理  稍后我看看提个pr进来
